# Area of the complex plane given by two numbers 'min' and 'max'
minRe: -1.5
minIm: -1.5
maxRe: 1.5
maxIm: 1.5
# Max amount of iterations (iteration depth)
nMax: 100
# Color (hexadecimal representation) for points inside of the mandelbrot set
innerColor: 0
# Color gradient (hexadecimal representation) for points outside of the mandelbrot set
# > First color for n_max-1 iterations reached
# > Last color for 0 iterations reached
# At least one color must be specified
colorGradient: [14811378, 16777215, 0, 16777215]
